baseURL = "http://localhost:1313/"
languageCode = "en-gb"
title = "Todmorden Events"
theme = "stack"
publishDir = "docs"

[pagination]
pagerSize = 20

mainSections = ["events"]

# [build]
# future = true

buildFuture = true
buildDrafts = false
buildExpired = false
